# Generated by Django 5.2.9 on 2026-05-23 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_districtnews_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyreport',
            name='district',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='emergency_type',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='verified_by',
        ),
        migrations.CreateModel(
            name='StaffResourceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_satisfied', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(help_text='e.g., kg, packets, units', max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.resourcecategory')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.district')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='DonationOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_phone', models.CharField(max_length=20)),
                ('donor_type', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('need_assistance', models.BooleanField(default=False)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Assigned', 'Volunteer Assigned'), ('Collected', 'Collected by Volunteer'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.volunteer')),
                ('donor_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staffresourcerequirement')),
            ],
        ),
        migrations.DeleteModel(
            name='DistrictAlert',
        ),
        migrations.DeleteModel(
            name='EmergencyType',
        ),
        migrations.DeleteModel(
            name='EmergencyReport',
        ),
    ]
