# Generated by Django 5.2.9 on 2026-05-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_emergencyreport_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationoffer',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donationoffer',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffresourcerequirement',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffresourcerequirement',
            name='location_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffresourcerequirement',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
