# Generated by Django 5.2.9 on 2025-12-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profile'),
        ),
    ]
