# Generated by Django 5.2.9 on 2026-02-06 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_department_remove_complaint_assigned_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_days', models.IntegerField(help_text='Typical processing time in days')),
                ('required_documents', models.TextField(help_text='List of required documents')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='department',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='report',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintaction',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaintaction',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='loginid',
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='reply',
            new_name='admin_reply',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('Service', 'Service Quality'), ('Authority', 'Authority Performance'), ('System', 'System/Website'), ('General', 'General Feedback')], default='General', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='Rating from 1 to 5'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=200)),
                ('office_address', models.CharField(max_length=300)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='authority_profile')),
                ('status', models.CharField(default='active', max_length=40)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Authorities',
            },
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('applicant_mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('applicant_dob', models.DateField(blank=True, null=True)),
                ('applicant_address', models.TextField()),
                ('additional_details', models.TextField(blank=True, help_text='Additional details specific to certificate type', null=True)),
                ('document1', models.FileField(blank=True, null=True, upload_to='certificate_documents')),
                ('document2', models.FileField(blank=True, null=True, upload_to='certificate_documents')),
                ('document3', models.FileField(blank=True, null=True, upload_to='certificate_documents')),
                ('document4', models.FileField(blank=True, null=True, upload_to='certificate_documents')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Forwarded', 'Forwarded to Authority'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Issued', 'Certificate Issued')], default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('forwarded_date', models.DateTimeField(blank=True, null=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.authority')),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.certificatetype')),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('certificate_file', models.FileField(upload_to='issued_certificates')),
                ('service_amount', models.DecimalField(decimal_places=2, help_text='Final service fee', max_digits=10)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('validity_period', models.CharField(blank=True, help_text='e.g., Lifetime, 5 years', max_length=100, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificate_qr')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.authority')),
                ('certificate_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.certificaterequest')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='certificate_request',
            field=models.ForeignKey(blank=True, help_text='Leave blank for general feedback', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.certificaterequest'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='customer_profile')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Online', 'Online Payment'), ('Cash', 'Cash'), ('Card', 'Debit/Credit Card'), ('UPI', 'UPI')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('certificate_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.certificaterequest')),
            ],
        ),
        migrations.DeleteModel(
            name='Citizen',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='ComplaintAction',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
