# Generated by Django 5.2.9 on 2026-02-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_adminnotice_news_scheme_customer_status_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
