# Generated by Django 5.2.9 on 2026-05-09 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_scheme_end_date_scheme_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='citizen_profile')),
                ('status', models.CharField(default='active', max_length=40)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(default='Kerala', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('alert_level', models.CharField(choices=[('Red', 'Red Alert (Extreme Danger)'), ('Orange', 'Orange Alert (High Risk)'), ('Yellow', 'Yellow Alert (Precaution)'), ('Green', 'Green (Safe/Update)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.district')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_details', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='emergency_reports')),
                ('status', models.CharField(choices=[('Pending', 'Pending Verification'), ('Verified', 'Verified'), ('Active', 'Rescue Operations Ongoing'), ('Resolved', 'Situation Resolved'), ('Fake', 'Fake Report')], default='Pending', max_length=50)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(default='')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='emergency_icons')),
            ],
        ),
        migrations.CreateModel(
            name='RescueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=20)),
                ('number_of_people', models.IntegerField(default=1)),
                ('priority', models.CharField(choices=[('High', 'High (Life Threatening)'), ('Medium', 'Medium (Injured/Trapped)'), ('Low', 'Low (Stranded/Needs Supplies)')], default='Medium', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='staff_profile')),
                ('status', models.CharField(default='active', max_length=40)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.district')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('skills', models.TextField(default='', help_text='e.g., First Aid, Swimming, Driving')),
                ('availability_status', models.CharField(default='Available', max_length=50)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='volunteer_profile')),
                ('status', models.CharField(default='Pending', max_length=40)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.district')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminNotice',
        ),
        migrations.RemoveField(
            model_name='authority',
            name='loginid',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='assigned_authority',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_request',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='certificate_type',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='certificate_request',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='certificate_request',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='loginid',
        ),
        migrations.RemoveField(
            model_name='schemeapplication',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='customer',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='schemeapplication',
            name='scheme',
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_type',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='General', max_length=200),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.citizen'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.district'),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.citizen'),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='emergency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.emergencytype'),
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.emergencyreport'),
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.citizen'),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.staff'),
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='assigned_volunteers',
            field=models.ManyToManyField(blank=True, to='myapp.volunteer'),
        ),
        migrations.DeleteModel(
            name='Authority',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='CertificateType',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='CertificateRequest',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Scheme',
        ),
        migrations.DeleteModel(
            name='SchemeApplication',
        ),
    ]
