# Generated by Django 5.2.9 on 2026-05-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_citizen_district_emergencyalert_emergencyreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
