# Generated by Django 5.2.9 on 2026-05-15 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_resourcecategory_resourcestock_userresourcerequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtnews',
            name='district',
        ),
        migrations.RemoveField(
            model_name='districtnews',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='district',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rescuerequest',
            name='assigned_volunteers',
        ),
        migrations.RemoveField(
            model_name='rescuerequest',
            name='district',
        ),
        migrations.RemoveField(
            model_name='rescuerequest',
            name='report',
        ),
        migrations.RemoveField(
            model_name='rescuerequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='urgentworkrequest',
            name='district',
        ),
        migrations.RemoveField(
            model_name='urgentworkrequest',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='urgentworkresponse',
            name='request',
        ),
        migrations.RemoveField(
            model_name='urgentworkresponse',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='userresourcerequest',
            name='last_update',
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Resolved', 'Resolved'), ('Fake', 'Fake')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='resourcestock',
            name='unit',
            field=models.CharField(help_text='e.g., kg, liters, units', max_length=50),
        ),
        migrations.AlterField(
            model_name='userresourcerequest',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='DistrictAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('alert_level', models.CharField(choices=[('Red', 'Critical'), ('Orange', 'High'), ('Yellow', 'Precaution'), ('Green', 'Update/Normal')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.district')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='DistrictNews',
        ),
        migrations.DeleteModel(
            name='EmergencyAlert',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='RescueRequest',
        ),
        migrations.DeleteModel(
            name='UrgentWorkRequest',
        ),
        migrations.DeleteModel(
            name='UrgentWorkResponse',
        ),
    ]
